version: '3.8'

services:
  database:
    image: mongo:4.4
    container_name: db
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: administrator
      MONGO_INITDB_ROOT_PASSWORD: administrator