name: Docker Build and Push

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  push_to_registry:
    name: Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: garyascuy/money:latest

      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
          